import type { Metadata } from "next";
import localFont from "next/font/local";
import { Raleway } from 'next/font/google'

import ThemeProvider from "@/Providers/ThemeProvider";

//css
import "./globals.css";
import { Container } from "./home/index.styles";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const raleway = Raleway({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // Adjust weights as needed
  variable: '--font-raleway',
  display: 'swap',
})

const beautyRachela = localFont({
  src: [
    {
      path: "../../public/fonts/beauty-rachela/BeautyRachela-Regular.otf",
      weight: "400",
      style: "normal",
    },
  ],
});

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body
        className={`${raleway.className} ${beautyRachela.className}antialiased`}
      >
        <ThemeProvider>
          <Container>{children}</Container>
        </ThemeProvider>
      </body>
    </html>
  );
}

export default RootLayout;