
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ThemeProvider from "@/Providers/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const raleway = localFont({
 src: [
  {
    path: '../../public/fonts/raleway/Raleway-Regular.ttf',
    weight: '400',
    style: 'normal',  
  }
 ]
})

const beautyRachela = localFont({
  src: [
    {
      path: '../../public/fonts/beauty-rachela/BeautyRachela-Regular.otf',
      weight: '400',
      style: 'normal',
    }
  ]
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`  ${raleway.className} ${beautyRachela.className}antialiased`}
      >
        <ThemeProvider>
        {children}
        </ThemeProvider>
        </body>
    </html>
  );
}
